<?php 
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://cloud.elastic.co/internal/security/login');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"providerType\":\"basic\",\"providerName\":\"cloud-basic\",\"currentURL\":\"https://cloud.elastic.co/login?next=%2Fapp%2Fmanagement\",\"params\":{\"username\":\"chari@fortidm.com\",\"password\":\"N0t@Re@lP@ssw0rd\"}}");  

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Kbn-Xsrf: true';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);


$response = json_decode($result,true);
echo '<pre>'; print_r($response); exit;
if(!empty($response) && isset($response['location'])) { ?>

    <script>
        document.location.href= 'https://test4-fortidm.kb.eastus2.azure.elastic-cloud.com:9243';
    </script>    

<?php }

?>