<?php

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://test-2.kb.eastus2.azure.elastic-cloud.com:9243/_security/user/jacknich?pretty');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, '{"password" : "l0ng-r4nd0m-p@ssw0rd","roles" : [],"full_name" : "Jack Nicholson","email" : "jacknich@example.com","metadata" : {"intelligence" : 7 }}');
curl_setopt($ch, CURLOPT_USERPWD, 'elastic:PBMeIk6pWJYMQvSoeHOUyld7');

$headers = array();
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
 
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
} 
curl_close($ch);

echo '<pre>'; print_r(json_decode($result)); exit;

?>